//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        
        public long StudentID { get; set; }

        [Required(ErrorMessage = "Student Name can't be Blank")]
        [MinLength(2)]
        [MaxLength(20)]
        public string FullName { get; set; }

        [Required(ErrorMessage = "User ID can't be blank")]
        [RegularExpression(@"^[A-Z]+[a-z]+[0-9]+$", ErrorMessage = "Insert Proper UserID e.g There Should be atlest 1 UpperCase character 1 LowerCase character\n 1 Digit")]
        public string UserID { get; set; }

        [Required(ErrorMessage = "EmailID can't be blank")]
        [EmailAddress(ErrorMessage = "Insert Valid EmailID")]
        public string EmailID { get; set; }

        [Required(ErrorMessage = "Insert Date OF Birth")]

        public Nullable<System.DateTime> DateOFBirth { get; set; }

        
        public string Gender { get; set; }

        [Required(ErrorMessage = "please Enter Address")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Enter Phone No.")]
        public string PhoneNo { get; set; }

        [Required(ErrorMessage = "Enter Your Previous Qualification")]
        public string PreviousQualification { get; set; }


        [Required(ErrorMessage = "Enter  your Course")]
        public Nullable<long> CourseID { get; set; }
        public string Photo { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
